# Generated by Django 5.0.7 on 2024-07-30 04:52

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('student_email', models.EmailField(max_length=100)),
                ('personal_email', models.EmailField(max_length=100)),
                ('locker_num', models.IntegerField()),
                ('locker_combination', models.CharField(max_length=9)),
                ('good_student', models.BooleanField(default=True)),
            ],
        ),
    ]
