# Generated by Django 5.0.7 on 2024-07-30 05:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student_app', '0002_alter_student_personal_email'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='student',
            name='locker_num',
        ),
        migrations.AddField(
            model_name='student',
            name='locker_number',
            field=models.IntegerField(default='1', unique=True),
        ),
        migrations.AlterField(
            model_name='student',
            name='locker_combination',
            field=models.CharField(blank=True, max_length=9),
        ),
        migrations.AlterField(
            model_name='student',
            name='name',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='student',
            name='personal_email',
            field=models.EmailField(max_length=100, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='student',
            name='student_email',
            field=models.EmailField(blank=True, max_length=100, unique=True),
        ),
    ]
