# Generated by Django 5.0.7 on 2024-07-23 05:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('student_app', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='student',
            name='good_student',
        ),
        migrations.RemoveField(
            model_name='student',
            name='locker_combination',
        ),
        migrations.RemoveField(
            model_name='student',
            name='locker_number',
        ),
        migrations.RemoveField(
            model_name='student',
            name='personal_email',
        ),
        migrations.RemoveField(
            model_name='student',
            name='student_email',
        ),
    ]
