# Generated by Django 5.0.7 on 2024-07-23 05:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student_app', '0004_alter_student_name_alter_student_student_email'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='good_student',
            field=models.BooleanField(),
        ),
        migrations.AlterField(
            model_name='student',
            name='locker_combination',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='student',
            name='locker_number',
            field=models.IntegerField(),
        ),
    ]
