# Generated by Django 5.0.7 on 2024-07-24 03:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student_app', '0008_alter_student_locker_combination_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='good_student',
            field=models.BooleanField(),
        ),
        migrations.AlterField(
            model_name='student',
            name='locker_combination',
            field=models.CharField(default='12-12-12', max_length=8),
        ),
        migrations.AlterField(
            model_name='student',
            name='personal_email',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
