# Generated by Django 5.0.7 on 2024-07-24 03:40

import student_app.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student_app', '0011_alter_student_locker_combination'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='locker_combination',
            field=models.CharField(default='12-12-12', max_length=20, validators=[student_app.validators.validate_combination_format]),
        ),
        migrations.AlterField(
            model_name='student',
            name='student_email',
            field=models.CharField(max_length=100, unique=True, validators=[student_app.validators.validate_school_email]),
        ),
    ]
