# Generated by Django 5.0.7 on 2024-07-24 04:09

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student_app', '0016_remove_student_personal_email_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='personal_email',
            field=models.EmailField(default='', max_length=254, unique=True),
        ),
        migrations.AlterField(
            model_name='student',
            name='name',
            field=models.CharField(max_length=100, validators=[django.core.validators.RegexValidator(message='Name must be in the format "First Middle Initial. Last"', regex='^[A-Za-z]+\\s[A-Za-z]\\.\\s[A-Za-z]+$')]),
        ),
        migrations.AlterField(
            model_name='student',
            name='student_email',
            field=models.EmailField(default='', max_length=254, unique=True),
        ),
    ]
