# Generated by Django 5.0.7 on 2024-07-24 04:09

import student_app.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student_app', '0017_student_personal_email_alter_student_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='student_email',
            field=models.EmailField(default='', max_length=254, unique=True, validators=[student_app.validators.validate_school_email]),
        ),
    ]
